# This is a basic workflow to help you get started with Actions

name: Price Ticker

on:
  workflow_dispatch:
  schedule:
    - cron: '* */2 * * *'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: nodeModules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install packages
        run: yarn --frozen-lockfile
        env:
          CI: true

      - name: Send Email
        run: node usdtTicket.js
        env:
          HOST_STRING: ${{secrets.HOST_STRING}}
          PORT_NUMBER: ${{secrets.PORT_NUMBER}}
          FROM_USER: ${{secrets.FROM_USER}}
          FROM_PASSWORD: ${{secrets.FROM_PASSWORD}}
          TO_USER: ${{secrets.TO_USER}}
          CI: true
